### ISSUE TITLE
Issues with the chosen license (LGPL3+)

### ISSUE THREAD

**Issue by hillu** [hillu/linux-audit-parser-rs#1]
In https://github.com/threathunters-io/laurel/issues/224#issuecomment-2313150363, @jszwedko stated:
> My understanding is that users using Vector or VRL in their own projects that they distribute would need to either open source their code with an acceptable license or distribute the resulting artifacts in a way that the LGPL code could be modified and reincluded.

While we seem to agree in principle on the restriction, I think that this restriction only concerns authors of combined works who do not want to provide source for their work. And even then, it's merely a technical issue that can be overcome by offering some clever linker script to end-users. This issue will get even easier to overcome as soon as Rust grows a stable ABI.

I chose the LGPL because I find it important that bug fixes and enhancements (however insignificant they may seem) are made available under the same terms as the original code. To my knowledge, Apache-2.0 cannot be used to enforce this. MIT and BSD licenses certainly can't.

Of course, I'm open to other suggestions.

**Comment by jorgehermo9** [comment]
I think that in practice, if someone wants to build Vector with another version of this crate, that could be easily done editing its `Cargo.toml`, though it cannot be easily done on runtime (dynamic linking). 

In the case of VRL, they could use patched dependencies https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html if this `linux-audit-parser-rs` crates happens to be a transitive dependency of their program (which would happend for all programs depending on the [VRL crate](https://crates.io/crates/vrl))

I think that that complies with the LGPL requirements and therefore there is not additional work in order to enforce that for Vector/VRL? I'm not an expert in licensing so I may be wrong though...

**Comment by jszwedko** [comment]
Ah, yes, to clarify I mean it would place additional restrictions on projects that depend on Vector or VRL rather than Vector or VRL itself (which, as you note, people could easily recompile with the modified version of the dependency).

Projects depending on Vector or VRL would either need to be distributed as open source with a compatible license or, as @hillu is suggesting, recipients of the "Combined Work" sans source code would need to be able to modify the included linux-audit-parser-rs dependency somehow. This is the part I'm not entirely sure would look like in practice.

**Comment by jorgehermo9** [comment]
> I chose the LGPL because I find it important that bug fixes and enhancements (however insignificant they may seem) are made available under the same terms as the original code. To my knowledge, Apache-2.0 cannot be used to enforce this. MIT and BSD licenses certainly can't.

I think the MPL-2.0 complies with this. Modifications to the MPL-2.0 code should be made available as you require 
https://www.mozilla.org/en-US/MPL/2.0/FAQ/
(see Question 1)

**Comment by jszwedko** [comment]
> > I chose the LGPL because I find it important that bug fixes and enhancements (however insignificant they may seem) are made available under the same terms as the original code. To my knowledge, Apache-2.0 cannot be used to enforce this. MIT and BSD licenses certainly can't.
> 
> I think the MPL-2.0 complies with this. Modifications to the MPL-2.0 code should be made available as you require https://www.mozilla.org/en-US/MPL/2.0/FAQ/ (see Question 1)

Indeed, I think MPL-2.0 would still achieve this particular goal. Any changes to MPL-2.0 licensed code would need to be made available.

**Comment by jorgehermo9** [comment]
Hi @hillu, any thoughts about this?

**Comment by hillu** [comment]
@jorgehermo9 Yeah, I have been thinking a bit about the license.

The issue LGPL addresses and MPL does not is that users of a combined work should still be able to change the library (i.e. the audit parser in this case), even if they cannot build the entire combined work from sources. I think that users should have this freedom.

I think I'll leave the license as-is but add a note about what can be done about alternative arrangements.

For Rust projects that depend on this library, there'd always be the option to only use it if a certain feature flag is set.

**Comment by jorgehermo9** [comment]
Understood, thank you very much for your response, I really appreciate that.

Should we wait then to the note you will add so we can procede with what you suggest?

I don't know if this fits the Vector project @jszwedko. I don't think that is feasible to ship Vector with dynamic linking (I can't think of any other alternatives to comply with LGPL). If not, we should work in a completely new parser.

**Comment by hillu** [comment]
I find that adding any vague note that boils down to contacting the author and contributors looks ethically questionable, so let's not do that. To be clear, I don't want to make this about money going to me - I'd consider that ethically questionable at best, too. (Gee, picking a different license might have meant less of a headache, who knew?)

I don't think that we should discuss license exceptions for distributing specific binary-only builds of Vector in public – but my e-mail address can be found at the bottom of the README file.

**Comment by jszwedko** [comment]
Thanks for the additional thoughts @hillu .

@jorgehermo9 I think we _could_ still use this library in Vector so long as we put it behind a feature flag so that it can be excluded when Vector is used in a "Combined Work" where the author of the "Combined Work" isn't able to comply with LGPL (which I believe, in this case, would mean distributing the entire source of the combined work so that it could be recompiled with a modified version of this library). I'd want to validate my understanding further before we move in that direction though.

Dynamic linking of this library in Vector, somehow, would be another option but I'm still not quite sure what this would look like.

**Comment by jorgehermo9** [comment]
Oh, I understand now. In cases where the LGPL can't be complied with (for example, in close source projects), the functionality of the `linux-audit-parser` crate wouldn't be available to use at all for the end-users, because Vector would be compiled without that crate, so there is no need for dynamic linking at all.

And then, open source projects could use `linux-audit-parser` as regular.

I have a few doubts about it... How will Vector distribution be done? Would you distribute two versions, one LGPL-compliant and other without the `linux-audit-parser` crate? :thinking:

**Comment by jszwedko** [comment]
Right, yeah, I think for Vector itself, the LGPL license is compatible as we already distribute Vector's source and so users could modify `linux-audit-parser` and recompile Vector with those modification and so there is no need to distribute multiple Vector versions. My concern is with consumers of Vector as a crate where they don't, themselves, distribute the source. I believe this usage would require not including the `linux-audit-parser` crate (or it would need to be included in a way that could be modified) which is where the Vector feature flag would come in handy: to be able to opt into the LGPL dependencies only when able to comply with the license.

**Comment by jorgehermo9** [comment]
Everything is clear then! You can close this if you want @hillu

**Comment by jorgehermo9** [comment]
Hi @hillu. We finally decided to not include this library in Vector due to licensing issues. You can find the final decision [here](https://github.com/vectordotdev/vrl/pull/1010#issuecomment-2433984045).

I really appreciate your work on this and I totally hope that someone else find this crate useful. Due to the licensing issue, I may end up writing my own parser (with no inspiration from yours, of course) with a MPL/Apache/MIT-compatible license. 

I'm sorry for all the inconveniences and thank you very much for your work and time.
